<a href="https://colab.research.google.com/github/HoangTung99/CS114.L11.KHCL/blob/master/TestModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


**Test && Rate**

In [ ]:
import tensorflow as tf
import numpy as np
import cv2
import os
from keras.models import model_from_json

In [ ]:
# dataset 1
path_dir_data_1 = "drive/MyDrive/HalfOf_DataSet_CS114"
path_dir_data_test_1 = f"{path_dir_data_1}/test"

# dataset 2
path_dir_data_2 = "drive/MyDrive/DataSet_CS114"
path_dir_data_test_2 = f"{path_dir_data_2}/test"

# models
path_dir_model = "drive/MyDrive/models"

# list of emotions
emotions = ['angry', 'fear', 'happy', 'neutral', 'sad', 'surprise']

In [ ]:
for i in range(1, 12):
  print(f"model_{i}")

  total_img = 0
  total_correct_pred = 0

  #load model  
  model = model_from_json(open(f"{path_dir_model}/model_{i}/model.json", "r").read())  
  #load weights
  model.load_weights(f"{path_dir_model}/model_{i}/model_weights.h5")

  path_dir_data_test = path_dir_data_test_1

  if i > 6:
    path_dir_data_test = path_dir_data_test_2

  for expression in os.listdir(path_dir_data_test):
    total_expression += 1
    print(expression+"...")
    for img_name in os.listdir(f"{path_dir_data_test}/{expression}"):
      total_img += 1

      test_img = cv2.imread(f"{path_dir_data_test}/{expression}/{img_name}")
      test_img = test_img * 1.0
      pred = tf.expand_dims(test_img, axis=0)

      predictions = model.predict(pred) 
      if expression == emotions[np.argmax(predictions[0])]:
        total_correct_pred += 1


  print(f"Accuracy on test images: {total_correct_pred/total_img}")
  print("======================================================\n")

model_1
sad...
neutral...
happy...
angry...
fear...
surprise...
Accuracy on test images: 0.5107843137254902

model_2
sad...
neutral...
happy...
angry...
fear...
surprise...
Accuracy on test images: 0.4774509803921569

model_3
sad...
neutral...
happy...
angry...
fear...
surprise...
Accuracy on test images: 0.5852941176470589

model_4
sad...
neutral...
happy...
angry...
fear...
surprise...
Accuracy on test images: 0.5950980392156863

model_5
sad...
neutral...
happy...
angry...
fear...
surprise...
Accuracy on test images: 0.5725490196078431

model_6
sad...
neutral...
happy...
angry...
fear...
surprise...
Accuracy on test images: 0.5401960784313725

model_7
angry...
fear...
happy...
sad...
neutral...
surprise...
Accuracy on test images: 0.6019607843137255

model_8
angry...
fear...
happy...
sad...
neutral...
surprise...
Accuracy on test images: 0.6009803921568627

model_9
angry...
fear...
happy...
sad...
neutral...
surprise...
Accuracy on test images: 0.6313725490196078

model_10
angry...
f

In [ ]:
for i in range(1, 30):
  # load photo
  test_img = cv2.imread(f"drive/MyDrive/DataSet_CS114_One/test/angry/angry_test_{i}.jpg")

  test_img = test_img * 1.0
  pred = tf.expand_dims(test_img, axis=0)

  predictions = model.predict(pred)
  print(np.argmax(predictions[0]))
  print(predictions)

4
[[5.7383053e-02 3.5863337e-03 2.9833431e-04 1.8974148e-01 7.4893856e-01
  5.2224630e-05]]
0
[[7.58981764e-01 7.82591775e-02 5.30412793e-03 9.87901259e-03
  1.47462323e-01 1.13579394e-04]]
0
[[0.72818315 0.02816666 0.16764288 0.02895978 0.04239624 0.00465126]]
0
[[9.7926122e-01 9.2740143e-03 7.8409020e-04 5.7044538e-04 2.6095791e-03
  7.5006266e-03]]
0
[[8.2194281e-01 1.2780190e-01 2.7466540e-05 6.4902278e-10 3.3524273e-08
  5.0227873e-02]]
0
[[9.9625885e-01 7.3565869e-04 7.1783288e-04 2.2285087e-05 9.1935019e-04
  1.3460125e-03]]
0
[[0.61129296 0.00067158 0.02724852 0.09628297 0.26370898 0.00079496]]
0
[[9.9759609e-01 1.6706277e-03 6.5145206e-05 4.0765756e-04 2.2550787e-04
  3.4994671e-05]]
0
[[9.9086970e-01 3.4302715e-03 1.3461022e-03 5.5376743e-04 2.7336515e-03
  1.0664553e-03]]
0
[[0.84635484 0.06029527 0.02944345 0.00413861 0.05874036 0.00102748]]
0
[[0.37352836 0.22046272 0.12781325 0.13640304 0.13036801 0.01142466]]
0
[[9.9812359e-01 9.2686241e-04 8.1243803e-07 9.3667688e-07 9.